FoodBhalluk/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restuarant.urls', namespace='resturant')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATICFILES_DIRS)

restuarant/urls.py
from django.urls import path

from .view import views

from restuarant.view.cart import Cart

app_name = 'resturant'

urlpatterns = [
    path('', views.Index.as_view(), name='pattern'),
    # path('', views.individual_food, name='pattern'),
    path('products/', views.product_list, name='product_list'),
    path('addcart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', Cart.as_view(), name='cart'),
]

restuarant/model/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=False)

    def __str__(self):
        return self.name


class Menu(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    MENU_CHOICES = (
        ("Appetisers", "Appetisers"),
        ("Salads", "Salads"),
        ("Starters", "Starters"),
        ("Main_Dishes", "Main_Dishes"),
    )
    title = models.CharField(max_length=50, choices=MENU_CHOICES)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()


    @staticmethod
    def get_item_by_id(ids):
        return Menu.objects.filter(id__in =ids)

    def __str__(self):
        return self.title

restuarant/view/views.py
from django.shortcuts import render, redirect
from restuarant.model.models import Menu

# New import for Cart
from django.views import View


# Class based views
class Index(View):

    def post(self, request):
        item = request.POST.get('item')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(item)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(item)
                    else:
                        cart[item] = quantity - 1
                else:
                    cart[item] = quantity + 1
            else:
                cart[item] = 1
        else:
            cart = {}
            cart[item] = 1
        request.session['cart'] = cart
        print(request.session['cart'])
        return redirect('resturant:pattern')

    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        appetisers = Menu.objects.filter(title='Appetisers')
        salads = Menu.objects.filter(title='Salads')
        starters = Menu.objects.filter(title='Starters')
        main_dishes = Menu.objects.filter(title='Main_Dishes')
        return render(request, 'restuarant/index.html',
                      {'Appetisers': appetisers,
                       'Salads': salads,
                       'Starters': starters,
                       'Main_Dishes': main_dishes})


# def individual_food(request):
#     # menu_foods = Menu.objects.all()
#     appetisers = Menu.objects.filter(title='Appetisers')
#     salads = Menu.objects.filter(title='Salads')
#     starters = Menu.objects.filter(title='Starters')
#     main_dishes = Menu.objects.filter(title='Main_Dishes')
#     return render(request, 'restuarant/index.html',
#                   {'Appetisers': appetisers,
#                    'Salads': salads,
#                    'Starters': starters,
#                    'Main_Dishes': main_dishes})


# Create your views here.


def product_list(request):
    return render(request, 'restuarant/sections/product_list.html')


def add_to_cart(request):
    return render(request, 'restuarant/sections/cart.html')

restuarant/views.py
from django.shortcuts import render, redirect
from restuarant.models import Menu

# New import for Cart
from django.views import View


# Class based views
class Index(View):

    def post(self, request):
        item = request.POST.get('item')
        remove = request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(item)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(item)
                    else:
                        cart[item] = quantity - 1
                else:
                    cart[item] = quantity + 1
            else:
                cart[item] = 1
        else:
            cart = {}
            cart[item] = 1
        request.session['cart'] = cart
        print(request.session['cart'])
        return redirect('resturant:pattern')

    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        appetisers = Menu.objects.filter(title='Appetisers')
        salads = Menu.objects.filter(title='Salads')
        starters = Menu.objects.filter(title='Starters')
        main_dishes = Menu.objects.filter(title='Main_Dishes')
        return render(request, 'restuarant/index.html',
                      {'Appetisers': appetisers,
                       'Salads': salads,
                       'Starters': starters,
                       'Main_Dishes': main_dishes})


# def individual_food(request):
#     # menu_foods = Menu.objects.all()
#     appetisers = Menu.objects.filter(title='Appetisers')
#     salads = Menu.objects.filter(title='Salads')
#     starters = Menu.objects.filter(title='Starters')
#     main_dishes = Menu.objects.filter(title='Main_Dishes')
#     return render(request, 'restuarant/index.html',
#                   {'Appetisers': appetisers,
#                    'Salads': salads,
#                    'Starters': starters,
#                    'Main_Dishes': main_dishes})


# Create your views here.


def product_list(request):
    return render(request, 'restuarant/sections/product_list.html')


def add_to_cart(request):
    return render(request, 'restuarant/sections/cart.html')

restuarant/templates/restuarant/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Restaurant</title>
    <link href="https://fonts.googleapis.com/css2?family=Gentium+Book+Basic:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Yeseva+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Yeseva+One&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;0,700;1,400;1,600;1,700&display=swap"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{% static "css/product_list_style.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
{#    <script src="https://code.jquery.com/jquery-3.6.0.js"#}
{#            integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
</head>

<body>

{% block content %}

{% endblock %}
</body>
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>


</html>

restuarant/templates/restuarant/index.html
{% extends 'restuarant/base.html' %}
{% load static %}
{% load cart %}

{% block content %}

    <div class="preloader">
        <div class="load">
            <hr/>
            <hr/>
            <hr/>
            <hr/>
        </div>
    </div>


    <!-------nav part goes here---------->
    <nav class="nav">
        <div class="container navbar">
            <div class="logo">
                <img src="{% static 'images/logo.png' %}" alt='logo'>
            </div>
            <div class="menu">
                <ul>
                    <li><a data-scroll href="#banner">Home</a></li>
                    <li><a data-scroll href="#food">about</a></li>
                    <li><a data-scroll href="#ingredients">ingredients</a></li>
                    <li><a data-scroll href="#pattern">menu</a></li>
                    <li><a data-scroll href="#review">reviews</a></li>
                    <li><a data-scroll href="#form">reservations</a></li>
                    <li><a id="cart" data-scroll href="#cart">Cart</a></li>
{#                    <li><button id="cart" data-scroll href="#cart">Cart</button></li>#}
                </ul>
            </div>
        </div>
    </nav>

    <!------------banner part goes here------------->

    <section id="banner">
        <div class="container banner">
            <div class="text">
                <h1>the right ingredients for the right food</h1>
                <img src="{% static 'images/restaurant-Recovered.png' %}" alt='restaurant'>

                <div class="tag">
                    <a href="#">BOOK A TABLE</a>
                    <a href="#">SET THE MENU</a>
                </div>
            </div>
        </div>
    </section>

    <!----------food part goes here-------->
    {% include 'restuarant/sections/food.html' %}


    <!--------ingredients part goes here---------->
    {% include 'restuarant/sections/ingredients.html' %}


    <!----------pattern part goes here----------->
    {% include 'restuarant/sections/pattern.html' %}


    <!--------Cart part goes here---->

    <section id="cart">
        <div class="container layer">
            <div class="cart-main">
                <ul>
                    <li><a href="index.html">Foods</a></li>
                    <li><a href="{% url 'resturant:product_list' %}">Details</a></li>
                    <li class="cart">
                        <a href="sections/cart.html">
                            <i class="fa fa-basket"></i>Cart<span>0</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <div class="container cart-thing">
        <div class="cart-img">
            <img src="{% static 'images/biriyani.jpg' %}" alt='biriyani'/>
            <h3>Biriyani</h3>
            <h3>200Tk</h3>
            <a class="add-cart cart1" href="">Add Cart</a>
        </div>


        <div class="cart-img">
            <img src="{% static 'images/cherry.jpg' %}" alt="Cherry">
            <h3>Desert</h3>
            <h3>350Tk</h3>
            <a class=" add-cart cart2" href="{% url 'resturant:add_to_cart' %}">Add Cart</a>
        </div>


        <div class="cart-img">
            <img src="{% static 'images/cherry.jpg' %}" alt="Cherry">
            <h3>Desert</h3>
            <h3>350Tk</h3>
            <a class="add-cart cart3" href="#">Add Cart</a>
        </div>


        <div class="cart-img">
            <img src="{% static 'images/biriyani.jpg' %}" alt='biriyani'>
            <h3>Biriyani</h3>
            <h3>200Tk</h3>
            <a class="add-cart cart4" href="#">Add Cart</a>
        </div>

    </div>


    <!----------review part goes here------------>
    {% include 'restuarant/sections/review.html' %}


    <!-------------form part goes here--------------->
    {% include 'restuarant/sections/form.html' %}


    <!--------footer part goes here------------>
    {% include 'restuarant/sections/footer.html' %}


{% endblock %}

restuarant/templates/restuarant/sections/cart.html
{% extends 'restuarant/base.html' %}
{% load static %}
{% load cart %}
{% block content %}

    <div class="cart-page container">
        <table>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Subtotal</th>
            </tr>

            {% for item in items %}

                <tr>
                    <td>
                        <div class="cart-info">
                            <img src="{% static 'images/biriyani.jpg' %}">
                            <div>
                                <p>{{ item.name }}</p>
                                <small>price: {{ item.price }}Tk</small>
                                <br>
                                <a href="">Remove</a>
                            </div>
                        </div>
                    </td>
                    <td>{{ item|cart_quantity:request.session.cart }}</td>
                    <td>{{ item|price_total:request.session.cart }}Tk</td>
                </tr>
            {% endfor %}


        </table>

        <div class="total-price">
            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>{{ items|total_cart_price:request.session.cart }}TK</td>
                </tr>
            </table>
        </div>
    </div>

{% endblock %}

restuarant/templates/restuarant/sections/food.html
{% load static %}

<section id="food">
    <div class="container food-main">
        <div class="left">

            <h3>JUST THE RIGHT FOOD</h3>
            <img src="{% static 'images/restaurant.png' %}">

            <P>If you’ve been to one of our restaurants, you’ve seen – and tasted – what keeps our customers coming back
                for more. Perfect materials and freshly baked food, delicious Lambda cakes, muffins, and gourmet coffees
                make us hard to resist! Stop in today and check us out!</P>

            <div class="left-logo">
                <img src="{% static 'images/man.png' %}">
            </div>

        </div>
        <div class="right">
            <img src="{% static 'images/dish.png' %}">
        </div>

    </div>
</section>

restuarant/templates/restuarant/sections/footer.html
{% load static %}

<footer>
        <div class="container foot-main">

            <div class="foot-item item1 ">
                <h3>About Us</h3>
                <img src="{% static 'images/photo.png' %}">

                <p>Lambda's new and expanded Chelsea location represents a truly authentic <b>Greek</b> patisserie,
                    featuring breakfasts of fresh croissants and steaming bowls of café.</p>
                <p>Lamda the best restaurant in town</p>

            </div>
            <div class="foot-item">
                <h3>Opening hours</h3>
                <img src="{% static 'images/photo.png' %}">
                <div class="foot-para2">
                    <p>Mon-Thu: 7:00am-8:00pm </p>
                    <p> Fri-Sun: 7:00am-10:00pm</p>
                    <img src="{% static 'images/card.png' %}">
                </div>
            </div>
            <div class="foot-item">
                <h3>Our location</h3>
                <img src="{% static 'images/photo.png' %}">
                <div class="foot-para3">
                    <p>19th Paradise Street Sitia</p>
                    <p> 128 Meserole Avenue</p>
                </div>
                <div class="social-media">
                    <i class="fa fa-facebook"></i>
                    <i class="fa fa-youtube tina"></i>
                    <i class="fa fa-twitter"></i>
                </div>
            </div>
        </div>
    </footer>

restuarant/templates/restuarant/sections/form.html
{% load static %}

<section id="form">
    <div class="container form-main">
        <div class="form-item">

            <div class="form-left">

                <div class="form-pic1">
                    <img src="{% static 'images/biriyani.jpg' %}" alt="">
                </div>

                <div class="form-pic1">
                    <img src="{% static 'images/cherry.jpg' %}" alt="">
                </div>
            </div>


            <div class="form-right">

                <div class="form-heading">
                    <h2>Just the right food</h2>
                    <img src="{% static 'images/pattern.png' %}" alt="">

                    <p>If you’ve been to one of our restaurants, you’ve seen – and tasted – what keeps our customers
                        coming back for more. Perfect materials and freshly baked food.</p>

                    <p> Delicious Lambda cakes, muffins, and gourmet coffees make us hard to resist! Stop in today and
                        check us out! Perfect materials and freshly baked food.</p>

                </div>

                <div class="form-content">
                    <div class="left-content">
                        <div class="content-item">
                            <h3>name</h3>
                            <form action="#" method="post">
                                <input type="text" placeholder="your name *">
                            </form>
                        </div>

                        <div class="content-item mina">
                            <h3>date</h3>
                            <form action="#" method="post">
                                <input type="text" placeholder="date *">
                                <i class="fa fa-calendar" aria-hidden="true"></i>
                            </form>
                        </div>
                    </div>

                    <div class="right-content">

                        <div class="content-item">
                            <h3>name</h3>
                            <form action="#" method="post">
                                <input type="text" placeholder="your name *">
                            </form>
                        </div>

                        <div class="content-item mina">
                            <h3>party number</h3>
                            <form action="#" method="post">
                                <input type="text" placeholder="party number">
                                <i class="fa fa-angle-down" aria-hidden="true"></i>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="btn">
                    <a href="#">Book now!</a>
                </div>
            </div>
        </div>
    </div>
</section>


<a class="back-To-Top">
    <i class="fa fa-chevron-up"></i>
</a>

restuarant/templates/restuarant/sections/ingredients.html
{% load static %}

<section id="ingredients">

    <div class="container ingredients-main">
        <div class="ingredients-item">

            <h3>Fine ingredients</h3>
            <img src="{% static 'images/photo.png' %}">
            <p>If you’ve been to one of our restaurants, you’ve seen – and tasted – what keeps our customers coming back
                for more. Perfect materials and freshly baked food, delicious Lambda cakes, muffins, and gourmet coffees
                make us hard to resist! Stop in today and check us out! </p>
            <div class="ingredients-menu">
                <div class="ingredients-pic">
                    <img src="{% static 'images/pic1.png' %}" alt="">
                </div>

                <div class="ingredients-pic chili">
                    <img src="{% static 'images/pic2.png' %}">
                </div>

                <div class="ingredients-pic">
                    <img src="{% static 'images/pic3.png' %}">
                </div>
            </div>
        </div>
    </div>


</section>

restuarant/templates/restuarant/sections/p_list.html
{% load static %}
<div class="tools">
    <div class="search-area">
        <input type="text" id="search" placeholder="Search"/>
        <button id="searchbutton">Go</button>
    </div>
</div>

<div class="pattern-header">
    <h3>Appetisers</h3>
    <img src="{% static 'images/pattern.png' %}" alt="">
</div>

<div class="products products-table">
    <div class="product">
        <div class="product-img">
            <img src="http://placehold.it/400x650"/>
        </div>
        <div class="product-content">
            <h3>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit
                <small>Consectetur Adipisicing</small>
            </h3>
            <p class="product-text price">$9.99</p>
            <p class="product-text genre">DVD Rental</p>
        </div>
    </div>
</div>

restuarant/templates/restuarant/sections/pattern.html
{% load static %}

{% load cart %}

<section id="pattern">
    <div class="container pattern">
        <div class="pattern-left">

            <div class="pattern-header">
                <h3>Appetisers</h3>
                <img src="{% static 'images/pattern.png' %}" alt="">
            </div>

            {% for apps in Appetisers %}
                <div id="{{ apps.id }}">
                    <div class="pattern-menu">
                        <h3 id="nm{{ apps.id }}">{{ apps.name }} <span>${{ apps.price }}</span></h3>
                        <p>{{ apps.description|truncatechars:60 }}</p>
                    </div>
                    <div class="AddToCart">
                        {% if apps|is_in_cart:request.session.cart %}
                            <div>
                                <form action="/#{{ apps.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ apps.id }}">
                                    <input hidden type="text" name="remove" value="True">
                                    <input type="submit" value=" - ">
                                </form>
                                <span>{{ apps|cart_quantity:request.session.cart }} in Cart</span>
                                <form action="/#{{ apps.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ apps.id }}">
                                    <input type="submit" value=" + ">
                                </form>
                            </div>
                        {% else %}
                            <form action="/#{{ apps.id }}" method="post">
                                {% csrf_token %}
                                <input hidden type="text" name="item" value="{{ apps.id }}">
                                <input type="submit" value="Add to cart">
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

            <div class="pattern-header">
                <h3>Salads</h3>
                <img src="{% static 'images/pattern.png' %}" alt="">
            </div>

            {% for Salad in Salads %}
                <div class="pattern-menu">
                    <h3>{{ Salad.name }} <span>${{ Salad.price }}</span></h3>
                    <p>{{ Salad.description|truncatechars:60 }}</p>
                </div>
                <div class="AddToCart">
                        {% if Salad|is_in_cart:request.session.cart %}
                            <div>
                                <form action="/#{{ Salad.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ Salad.id }}">
                                    <input hidden type="text" name="remove" value="True">
                                    <input type="submit" value=" - ">
                                </form>
                                <span>{{ Salad|cart_quantity:request.session.cart }} in Cart</span>
                                <form action="/#{{ Salad.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ Salad.id }}">
                                    <input type="submit" value=" + ">
                                </form>
                            </div>
                        {% else %}
                            <form action="/#{{ Salad.id }}" method="post">
                                {% csrf_token %}
                                <input hidden type="text" name="item" value="{{ Salad.id }}">
                                <input type="submit" value="Add to cart">
                            </form>
                        {% endif %}
                    </div>
            {% endfor %}

        </div>

        <div class="pattern-right">
            <div class="pattern-header">
                <h3>Starters</h3>
                <img src="{% static 'images/pattern.png' %}" alt="">
            </div>

            {% for Starter in Starters %}
                <div class="pattern-menu">
                    <h3>{{ Starter.name }}<span>${{ Starter.price }}</span></h3>
                    <p>{{ Starter.description }}</p>

                </div>
                <div class="AddToCart">
                        {% if Starter|is_in_cart:request.session.cart %}
                            <div>
                                <form action="/#{{ Starter.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ Starter.id }}">
                                    <input hidden type="text" name="remove" value="True">
                                    <input type="submit" value=" - ">
                                </form>
                                <span>{{ Starter|cart_quantity:request.session.cart }} in Cart</span>
                                <form action="/#{{ Starter.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ Starter.id }}">
                                    <input type="submit" value=" + ">
                                </form>
                            </div>
                        {% else %}
                            <form action="/#{{ Starter.id }}" method="post">
                                {% csrf_token %}
                                <input hidden type="text" name="item" value="{{ Starter.id }}">
                                <input type="submit" value="Add to cart">
                            </form>
                        {% endif %}
                    </div>
            {% endfor %}

            <div class="pattern-header">
                <h3>Main Dishes</h3>
                <img src="{% static 'images/pattern.png' %}" alt="">
            </div>

            {% for main_dish in Main_Dishes %}
                <div class="pattern-menu">
                    <h3>{{ main_dish.name }}<span>${{ main_dish.price }}</span></h3>
                    <p>{{ main_dish.description }}</p>
                </div>
                <div class="AddToCart">
                        {% if main_dish|is_in_cart:request.session.cart %}
                            <div>
                                <form action="/#{{ main_dish.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ main_dish.id }}">
                                    <input hidden type="text" name="remove" value="True">
                                    <input type="submit" value=" - ">
                                </form>
                                <span>{{ main_dish|cart_quantity:request.session.cart }} in Cart</span>
                                <form action="/#{{ apps.id }}" method="post">
                                    {% csrf_token %}
                                    <input hidden type="text" name="item" value="{{ main_dish.id }}">
                                    <input type="submit" value=" + ">
                                </form>
                            </div>
                        {% else %}
                            <form action="/#{{ main_dish.id }}" method="post">
                                {% csrf_token %}
                                <input hidden type="text" name="item" value="{{ main_dish.id }}">
                                <input type="submit" value="Add to cart">
                            </form>
                        {% endif %}
                    </div>
            {% endfor %}
        </div>
    </div>

</section>

restuarant/templates/restuarant/sections/product_list.html
{% extends 'restuarant/base.html' %}
{% load static %}
{% block content %}

    <!-- The search part -->
    <div class="tools">
        <div class="search-area">
            <input type="text" id="search" placeholder="Search"/>
            <button id="searchbutton">Go</button>
        </div>
    </div>

    <!-- The Appetisers part -->
    <div class="pattern-header">
        <h3>Appetisers</h3>
        <img src="{% static 'images/pattern.png' %}" alt="">
    </div>
{#    {% for apps in Appetisers %}#}
        <div class="products products-table">
            <div class="product">
                <div class="product-img">
                    <img src="http://placehold.it/400x650"/>
                </div>
                <div class="product-content">
                    <h3>
{#                        {{ apps.description|truncatechars:60 }}#}
                        <small>Consectetur Adipisicing</small>
                    </h3>
                    <p class="product-text price">$9.99</p>
                    <p class="product-text genre">DVD Rental</p>
                </div>
            </div>
        </div>
{#    {% endfor %}#}

{% endblock %}

restuarant/templates/restuarant/sections/review.html
{% load static %}

<section id="review">
    <div class="container review-main">
        <div class="review-item">
            <h3>guest reviews</h3>
            <img src="{% static 'images/photo.png' %}">
            <p>If you’ve been to one of our restaurants, you’ve seen – and tasted – what keeps our customers coming back
                for more. Perfect materials and freshly baked food, delicious Lambda cakes, muffins, and gourmet coffees
                make us hard to resist! Stop in today and check us out! </p>
            <h4> -food inc, New York </h4>
        </div>
    </div>
</section>

restuarant/templates/restuarant/sections/store.html
{%  extends 'store/index.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class ="thumbnail" src="{{ product.imageURL }}">
            <div class="box-element product">
              <h6><strong>{{ product.name }}</strong></h6>
            <hr>
            <button data-product={{ product.id }} data-action="add" class="btn
            btn-outline-secondary add-btn update-cart">Add to Cart</button>
            <a class ="btn btn-outline-success" href="#">View</a>
            <h4 style="display: inline-block;float: right">
                ${{ product.price|floatformat:2}}</h4>
        </div>
    </div>
       {% endfor %}
  </div>
{% endblock content %}